runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: home.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest